models:
  - name: products
    description: |
      Product dimension table. The grain of the table is one row per product.
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
